In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import matplotlib.pyplot as plt

# Creating the Dataset (from the given table)
data = pd.DataFrame({
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age':    [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male','Male','Male','Male','Male',
               'Female','Female','Female','Female','Female']
})

print(data.shape)
data.head(10)

(10, 4)

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [4]:
print(data.isnull().sum())
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})
data.head()

Weight    0
Height    0
Age       0
Gender    0
dtype: int64

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1

In [5]:
x = data[['Height', 'Age', 'Gender']].values
y = data['Weight'].values
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print('Predicted:', y_pred)
print('Actual   :', y_test)

Predicted: [56.85651025 79.10576115]
Actual   : [64 69]

In [6]:
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = metrics.r2_score(y_test, y_pred)
print('MSE  :', mse)
print('RMSE :', rmse)
print('R2 Score :', r2)
print('Intercept:', model.intercept_)
print('Coefficients (Height, Age, Gender):', model.coef_)

MSE  : 76.57792714844265
RMSE : 8.750881506936468
R2 Score : -11.252468343750825
Intercept: -3.0552172392595196
Coefficients (Height, Age, Gender): [32.8353363   0.31729474 14.62311848]

In [7]:
new_person = [[1.75, 30, 1]]
predicted_weight = model.predict(new_person)
print('Predicted Weight:', predicted_weight)

Predicted Weight: [78.54858202]